pub mod autoload;
pub mod cache;
pub mod composer;
pub mod config;
pub mod downloader;
pub mod error;
pub mod http;
pub mod installer;
pub mod json;
pub mod package;
pub mod plugin;
pub mod repository;
pub mod solver;

pub use error::{ComposerError, Result};
pub use package::Package;
pub use json::{ComposerJson, ComposerLock};
pub use repository::{Repository, RepositoryManager};
pub use solver::{Pool, Request, Solver, Policy, Transaction};
pub use downloader::{DownloadManager, DownloadResult};
pub use installer::{InstallationManager, InstallConfig};
pub use autoload::{AutoloadGenerator, AutoloadConfig};
pub use plugin::PluginRegistry;
pub use composer::Composer;
pub mod scripts;
