# syntax=docker/dockerfile:1
FROM rust:1.98-bullseye AS builder
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential ca-certificates cmake git pkg-config \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /work
COPY . .
ARG TARGET
RUN cargo build --release --locked --target "${TARGET}"
RUN strip "target/${TARGET}/release/pox"
RUN cp "target/${TARGET}/release/pox" /pox

FROM scratch
COPY --from=builder /pox /pox
