name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: namespace-profile-pox
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure Rust cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: |
            rust

      - name: Build
        run: cargo build --workspace --locked --verbose

      - name: Run tests
        run: cargo test --workspace --all-targets --locked --verbose
